### ISSUE TITLE
Error running /sedimentology stats

### ISSUE THREAD

**Issue by nullschritt** [sofar/Sedimentology#2]
(Error still occurs even with logiblocks removed)

Spigot-1.7.2-R02(Bukkit R02 API)

[01:00:49] [Server thread/INFO]: Stormageddon issued server command: /sedimentology stats
[01:00:49] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sedimentology' in plugin Sedimentology v8
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-1204]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:196) ~[craftbukkit.jar:git-Spigot-1204]
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:546) ~[craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.PlayerConnection.handleCommand(PlayerConnection.java:937) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:812) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.PacketPlayInChat.handle(PacketPlayInChat.java:65) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:147) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:259) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:540) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:446) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Spigot-1204]
Caused by: java.lang.NullPointerException
    at org.foo_projects.sofar.Sedimentology.Sedimentology$SedimentologyCommand.onCommand(Sedimentology.java:1050) ~[?:?]
    at plugin.bleachisback.LogiBlocks.FilterCommandListener.onCommand(FilterCommandListener.java:89) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-1204]
    ... 13 more

**Comment by sofar** [comment]
Is this run as a command by a player, or from the console with nobody logged in?

**Comment by sofar** [comment]
Not sure I understand what is actually going on here. The bug is that getLoadedChunks() is called for world "world". It's possible that no chunk is loaded in that world, but then the java error should be an invalid array index, not a nullpointer exception.

Do you not have a world named "world"?

In any case, this is certainly valid, and I'll have to fix the 2 problems in that codepath.

**Comment by sofar** [comment]
This should be fixed with 263e143

**Comment by nullschritt** [comment]
This is from a player logged in(me). There is no world named "world" nor is it referenced in the config.

**Comment by sofar** [comment]
Right, the fix will be in v10... Unfortunately I'm not expecting to do a release soon, so you may have to wait just a bit for it.

**Comment by sofar** [comment]
Was released 2 months ago.
